spring:
  servlet:
    multipart:
      max-file-size: 50MB
  config:
    import: optional:file:.env[.properties]
    activate:
      on-profile: dev
  datasource:
    url: ${DEV_MYSQL_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DEV_MYSQL_USER}
    password: ${DEV_MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 20
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  data:
    redis:
      host: redis
      port: 6379

logging:
  level:
    org:
      springframework:
        web: DEBUG

jwt:
  secret:
    key: ${JWT_SECRET_KEY}
  issuer: ${JWT_ISSUER}
  salt: ${JWT_SALT}
  access-token:
    expiretime: ${DEV_JWT_ACCESS_TOKEN_EXPIRETIME}
  refresh-token:
    expiretime: ${DEV_JWT_REFRESH_TOKEN_EXPIRETIME}

naver:
  secret:
    key: ${NAVER_SECRET_KEY}
  login-url: ${NAVER_LOGIN_URL}

cloud:
  aws:
    credentials:
      access-key: ${AWS_S3_ACCESS_KEY}
      secret-key: ${AWS_S3_SECRET_KEY}
    region:
      static: ${AWS_S3_BUCKET_REGION}
    stack:
      auto: false
    s3:
      bucket: ${AWS_S3_BUCKET_NAME}

fcm:
  type: ${FCM_TYPE}
  project-id: ${FCM_PROJECT_ID}
  private-key-id: ${FCM_PRIVATE_KEY_ID}
  private-key: ${FCM_PRIVATE_KEY}
  client-email: ${FCM_CLIENT_EMAIL}
  client-id: ${FCM_CLIENT_ID}
  auth-uri: ${FCM_AUTH_URI}
  token-uri: ${FCM_TOKEN_URI}
  auth_provider_x509_cert_url: ${FCM_AUTH_PROVIDER_CERT_URL}
  client_x509_cert_url: ${FCM_CLIENT_CERT_URL}
  universe_domain: ${FCM_UNIVERSE_DOMAIN}
